name: Keep Strapi Awake

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Strapi backend
        run: curl -s https://whimsical-renewal-84c9832818.strapiapp.com/api/products?pagination\[pageSize\]=1 > /dev/null
        # Added a simple query to ensure the DB connects as well as the server responding.
